version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Make output directory
          command: mkdir bin
      - run:
          name: Build & Test
          command: |
            VERSION_MAJOR_MINOR=0.0
            VERSION_BUILD=${CIRCLE_BUILD_NUM}
            VERSION=${VERSION_MAJOR_MINOR}.${VERSION_BUILD}
            echo ${VERSION} > bin/version.txt

            CMOCKA_MESSAGE_OUTPUT=xml CMOCKA_XML_FILE=../bin/cmocka.xml ./docker-make all

      - persist_to_workspace:
          root: bin
          paths:
            - version.txt
            - out.bin
            - cmocka.xml
      - store_test_results:
          path: bin

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./bin
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(cat ./bin/version.txt)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./bin/out.bin
workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - publish-github-release:
          requires:
            - hold
